spring.datasource.url: jdbc:mysql://localhost:3306/Test_schema?useSSL=false
spring.datasource.username: root
spring.datasource.password: password
#JPA settings
spring.jpa.hibernate.ddl_auto: create

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 120000 # a day
      refresh-token:
        expiration: 12000 # 7 days